#!/usr/bin/env bash
# Build condition D for one seed, from B's iteration-2000 checkpoint to D training.
#
# Usage: GPU=<index> bash assignments/hw1_ant/scripts/pipeline_d.sh <seed> [first_step]
#   first_step (default 1) resumes from a later step, e.g. 4 to recalibrate with existing data and model.
#
# Steps (plan sections 5.3, 5.4, 11):
#   1. wait for B_seed<S>/model_2000.pt and export its actor as the frozen base policy
#   2. collect flat_noisy, flat_det and dr_det rollouts
#   3. train the nominal dynamics model
#   4. calibrate alpha (gate G3), stop if it fails
#   5. create D's starting checkpoint (zero last layer, critic from B)
#   6. equivalence test with alpha = 0 (gate G4), stop if it fails
#   7. train D for 1000 iterations
#
# Do not edit this file while an instance is running: bash reads scripts while executing them.
set -euo pipefail

SEED="$1"
FIRST_STEP="${2:-1}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${HERE}/../../.." && pwd)"
RUN="${HERE}/isaac_run.sh"
export PRIORITY=high  # D is on the critical path: take free slots before C and A
LOGS="${REPO_ROOT}/logs/hw1_runlogs"
cd "${REPO_ROOT}"

log() { echo "[$(date '+%H:%M:%S')] seed ${SEED}: $*"; }
step() { (( FIRST_STEP <= $1 )); }

if step 1; then
    log "waiting for B_seed${SEED}/model_2000.pt"
    until ls logs/rsl_rl/ant_hw1/*_B_seed"${SEED}"/model_2000.pt > /dev/null 2>&1; do sleep 30; done
    log "1. export base policy"
    NO_SLOT=1 bash "${RUN}" "${LOGS}/D${SEED}_1_export.log" assignments/hw1_ant/scripts/export_base_policy.py --seed "${SEED}"
fi

if step 2; then
    for DATASET in flat_noisy flat_det dr_det; do
        log "2. collect ${DATASET}"
        bash "${RUN}" "${LOGS}/D${SEED}_2_collect_${DATASET}.log" assignments/hw1_ant/scripts/collect_rollouts.py \
            --headless --seed "${SEED}" --dataset "${DATASET}"
    done
fi

if step 3; then
    log "3. train dynamics"
    NO_SLOT=1 bash "${RUN}" "${LOGS}/D${SEED}_3_dynamics.log" assignments/hw1_ant/scripts/train_dynamics.py --seed "${SEED}"
fi

if step 4; then
    log "4. calibrate alpha (G3)"
    NO_SLOT=1 bash "${RUN}" "${LOGS}/D${SEED}_4_calibrate.log" assignments/hw1_ant/scripts/calibrate_alpha.py --seed "${SEED}"
    grep "\[RESULT\]" "${LOGS}/D${SEED}_4_calibrate.log"
    if ! grep -q "G3=PASS" "${LOGS}/D${SEED}_4_calibrate.log"; then
        log "G3 failed, stopping"
        exit 3
    fi
fi

if step 5; then
    log "5. residual init"
    NO_SLOT=1 bash "${RUN}" "${LOGS}/D${SEED}_5_init.log" assignments/hw1_ant/scripts/make_residual_init.py --seed "${SEED}"
fi

if step 6; then
    log "6. equivalence test (G4)"
    bash "${RUN}" "${LOGS}/D${SEED}_6_equivalence.log" assignments/hw1_ant/scripts/test_equivalence.py \
        --headless --seed "${SEED}" --alpha_mode zero
    grep "\[RESULT\]" "${LOGS}/D${SEED}_6_equivalence.log"
    if ! grep -q "G4 PASS" "${LOGS}/D${SEED}_6_equivalence.log"; then
        log "G4 failed, stopping"
        exit 4
    fi
fi

if step 7; then
    log "7. train D"
    bash "${RUN}" "${LOGS}/train_D_seed${SEED}.log" scripts/reinforcement_learning/rsl_rl/train.py \
        --task Isaac-Ant-Residual-DR-v0 --headless --seed "${SEED}" --run_name "D_seed${SEED}" \
        --resume --load_run "D_init_seed${SEED}" --checkpoint model_0.pt \
        "env.actions.joint_effort.base_policy_file=base_policy_seed${SEED}.pt" \
        "env.actions.joint_effort.dynamics_file=dynamics_seed${SEED}.pt"
fi
log "done"
